[obj] New schematic service [chg] upgrade ruby to 3.2.2, docker-compose.yml/Makefile  fine tune

diff --git a/docker/Makefile b/docker/Makefile
--- a/docker/Makefile
+++ b/docker/Makefile
@@ -1,6 +1,6 @@
 #!make
-  include .env
-  export $(shell sed 's/=.*//' .env)
+  include docker.env
+  export $(shell sed 's/=.*//' docker.env)
   include RELEASE
   export $(shell sed 's/=.*//' RELEASE)
   APP_SRC_PATH := $(realpath ../)
@@ -21,9 +21,22 @@
 help:
 	@grep '^[^#[:space:]].*:' Makefile
 
+
+# Check if JOBS_DIR exists and is not empty
+check_jobs_dir:
+	${INFO} "Checking job config paths ..."
+	@if [ ! -d "$(JOBS_DIR)" ]; then \
+		echo "Error: JOBS_DIR $(JOBS_DIR) does not exist"; \
+		exit 1; \
+	fi
+	@if [ -z "$(shell ls -A $(JOBS_DIR))" ]; then \
+		echo "Error: JOBS_DIR $(JOBS_DIR) is empty"; \
+		exit 1; \
+	fi
+
 # Concatenate all .env files in the directory into one file
-concat_env_files:
-	@echo "Concatenating environment files..."
+concat_env_files: check_jobs_dir
+	${INFO} "Concatenating environment files..."
 	@rm -f $(COMBINED_ENV_FILE)
 	@find $(JOBS_DIR) -name '*.env' -exec cat {} \; > $(COMBINED_ENV_FILE)
 
@@ -47,13 +60,24 @@ bash: concat_env_files
 #	docker run --rm -it --env-file $(COMBINED_ENV_FILE) -v $(APP_SRC_PATH):$(WORKDIR) $(IMAGE):$(TAG) /bin/bash
 	docker-compose exec -u ds app /bin/bash
 
+#: List docker images
+images:
+	${INFO} "Listing docker images."
+	docker images
+
 #: Remove docker images
 rmi:
 	${INFO} "Removing docker images."
 	docker rmi $$(docker images|grep ${REPO_PATH}${IMAGE} | grep ${TAG} |head -1 |awk '{print $$3}')
 
+#: List container
+ps:
+	${INFO} "List container processes."
+	docker-compose ps
+
 #: Bring up all containers
 all.up:
+	docker network create --driver bridge integration || true
 	${INFO} "Bring up all Containers "
 	docker-compose up -d db
 	docker-compose exec db /mssql-init/wait-for-it.sh db:1433 -t 60 -- /mssql-init/configure-db.sh
@@ -67,6 +91,7 @@ all.down:
 
 #: Bring up app containers
 app.up:
+	docker network create --driver bridge integration || true
 	${INFO} "Turn all containers down"
 	docker-compose up -d app
 	docker-compose ps
